### ISSUE TITLE
Is there a native dark mode option?

### ISSUE THREAD

**Issue by scottchiefbaker** [GeSHi/geshi-1.0#158]
ChatGPT directed me to GeSHi for syntax highlighting some Perl script. Seems to work great out of the box with a minimal configuration:

```php
// Initialize GeSHi
$geshi = new GeSHi($code, 'perl');

// Configure GeSHi
$geshi->enable_line_numbers(GESHI_NORMAL_LINE_NUMBERS);
$geshi->set_header_type(GESHI_HEADER_DIV);

print $geshi->parse_code();
```

It's 2025 though, and it'd be nice if there was a "dark mode" out-of-the-box. Doing some Google and documentation searches I'm not seeing an obvious answer for this. Surely someone out there has already done this, and it just needs to be documented?

**Comment by edent** [comment]
Here's how I do it in CSS. It inverts the colour scheme if a user has switched to dark mode.

```css
:root {
	--filter-invert-L: 0;
	--filter-invert-D: 1;
	--filter-invert:   var(--filter-invert-L);
}

@media (prefers-color-scheme: light) {
	:root {
		--filter-invert: var(--filter-invert-L);
	}
}
@media (prefers-color-scheme: dark) {
	:root {
		--filter-invert: var(--filter-invert-D);
	}
}

.wp-geshi-highlight code {
	filter: invert( var(--filter-invert) );
}
```

**Comment by scottchiefbaker** [comment]
I implemented that [here](https://www.perturb.org/code/syntax_highlight.php?file=pcg32.pl) but it doesn't seem to be working? Am I missing something?

**Comment by edent** [comment]
In CSS, `.wp-geshi-highlight code` means "target the element `code` with an ancestor of `class="wp-geshi-highlight"`

Your HTML is 

```html
<div class="mx-lg-5 mx-md-3 mx-1 mt-3">
	<div class="perl" ...
```

So, you could change the CSS to just be:

```css
.perl {
	filter: invert( var(--filter-invert) );
	background: white;
}
```

That will give light mode a white background, and normal coloured text - and dark mode will invert; so a black background with inverted colour text.

![Inverted colours](https://github.com/user-attachments/assets/9b948fe0-ce95-43c0-aadd-b8fe09a94b13)
